/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Conexion.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author HP1000
 */
public class Jugador extends javax.swing.JInternalFrame {

    /**
     * Creates new form Jugador
     */
    public Jugador() {
        initComponents();
        id_jugador.setVisible(false);

        getContentPane().setBackground(new java.awt.Color(255, 204, 153));
        //setForeground(new java.awt.Color(153,255,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        txtpasaporte = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtdebug = new javax.swing.JTextField();
        txtactual = new javax.swing.JTextField();
        txtcotizacion = new javax.swing.JTextField();
        cboposicion = new javax.swing.JComboBox<>();
        btnlimpiar = new javax.swing.JButton();
        id_jugador = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        txtcedula = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(new java.awt.Color(255, 204, 153));

        fondo.setBackground(new java.awt.Color(102, 255, 102));
        fondo.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FUTBOLISTAS");
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 140, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CEDULA:");
        fondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("APELLIDOS:");
        fondo.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("EDAD:");
        fondo.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("PASAPORTE");
        fondo.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("POSICION:");
        fondo.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("EQUIPO DEBUG:");
        fondo.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("EQUIPO ACTUAL:");
        fondo.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("COTIZACIÒN :");
        fondo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        btnguardar.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnguardar.setForeground(new java.awt.Color(204, 0, 0));
        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        fondo.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        btneliminar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        fondo.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        btnmodificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });
        fondo.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 440, -1, -1));

        btnsalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });
        fondo.add(btnsalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 440, -1, -1));

        txtpasaporte.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtpasaporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtpasaporteKeyTyped(evt);
            }
        });
        fondo.add(txtpasaporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 225, -1));

        txtapellidos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtapellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtapellidosKeyTyped(evt);
            }
        });
        fondo.add(txtapellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 232, -1));

        txtnombres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtnombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombresKeyTyped(evt);
            }
        });
        fondo.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 225, -1));

        txtedad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtedadActionPerformed(evt);
            }
        });
        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });
        fondo.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 190, -1));

        txtdebug.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtdebug.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdebugKeyTyped(evt);
            }
        });
        fondo.add(txtdebug, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 225, -1));

        txtactual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtactual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtactualKeyTyped(evt);
            }
        });
        fondo.add(txtactual, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 225, -1));

        txtcotizacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcotizacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcotizacionKeyTyped(evt);
            }
        });
        fondo.add(txtcotizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 225, -1));

        cboposicion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboposicion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELANTERO", "DEFENSA", "ARQUERO", "VOLANTE" }));
        fondo.add(cboposicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 130, -1));

        btnlimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        fondo.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, -1, -1));
        fondo.add(id_jugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 50, -1));

        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        fondo.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        txtcedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcedulaKeyTyped(evt);
            }
        });
        fondo.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("NOMBRES:");
        fondo.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 886, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        // TODO adeso qd your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
        Eliminar();
        Limpiar();
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        // TODO add your handling code here:
        Modificar();
        Limpiar();
       // Consultar();
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        Consultar();
        btnmodificar.setEnabled(true);
        btneliminar.setEnabled(true);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
        if (txtcedula.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR CEDULA");
            txtcedula.requestFocus();
            return;
        }
        if (txtnombres.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR NOMBRES");
            txtnombres.requestFocus();
            return;
        }
        if (txtapellidos.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR APELLIDOS");
            txtapellidos.requestFocus();
            return;
        }
        
        if (txtcotizacion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR COTIZACION");
            txtcotizacion.requestFocus();
            return;
        }

        if (txtedad.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR EDAD");
            txtedad.requestFocus();
            return;
        }

        if (txtdebug.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR EQUIPO DEBUG");
            txtdebug.requestFocus();
            return;
        }
        if (txtactual.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "INGRESAR EQUIPO ACTUAL");
            txtactual.requestFocus();
            return;
        }

        Grabar();
        Limpiar();
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txtnombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombresKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }

    }//GEN-LAST:event_txtnombresKeyTyped

    private void txtapellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtapellidosKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }

    }//GEN-LAST:event_txtapellidosKeyTyped

    private void txtactualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtactualKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }

    }//GEN-LAST:event_txtactualKeyTyped

    private void txtdebugKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdebugKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isDigit(c))) {

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ingresar solo cadena de caracteres por favor");
        }

    }//GEN-LAST:event_txtdebugKeyTyped

    private void txtcedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcedulaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtcedulaKeyTyped

    private void txtedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtedadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtedadActionPerformed

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtedadKeyTyped

    private void txtpasaporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasaporteKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtpasaporteKeyTyped

    private void txtcotizacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcotizacionKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((Character.isLetter(c))) {
            if (!(c > '.' & c < '.')) {
                evt.consume();
                getToolkit().beep();
                JOptionPane.showMessageDialog(null, "Ingresar solo numeros por favor");
            }
        }
    }//GEN-LAST:event_txtcotizacionKeyTyped

    public void Grabar() {

        try {
            Conexion con = new Conexion();
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("INSERT INTO jugador( nombres, apellidos, edad, pasaporte, posicion, equipo_debug,"
                    + "            equipo_actual, cotizacion, cedula) VALUES ( ?, ?, ?, ?, ?, ?,?, ?, ?)");

            //pst.setInt(1, Integer.parseInt(id_jugador.getText()));
            pst.setString(1, txtnombres.getText().toUpperCase());
            pst.setString(2, txtapellidos.getText().toUpperCase());
            pst.setInt(3, Integer.parseInt(txtedad.getText()));
            pst.setInt(4, Integer.parseInt(txtpasaporte.getText()));

            int seleccionado = cboposicion.getSelectedIndex();
            pst.setString(5, cboposicion.getItemAt(seleccionado));

            pst.setString(6, txtdebug.getText().toUpperCase());
            pst.setString(7, txtactual.getText().toUpperCase());
            pst.setDouble(8, Double.parseDouble(txtcotizacion.getText()));
            pst.setInt(9, Integer.parseInt(txtcedula.getText()));

            pst.executeQuery();
             JOptionPane.showMessageDialog(rootPane, "Jugador Guardado", "Confirmación", 2);
          //  JOptionPane.showConfirmDialog(this, "Jugador Guardado", "Confirmación", 2);
        } catch (SQLException exc) {
            // JOptionPane.showMessageDialog(null, exc, "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Modificar() {
        Conexion con = new Conexion();
        try {
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("UPDATE jugador SET nombres=?,apellidos=?,edad=?,pasaporte=?,"
                    + "posicion=?,equipo_debug=?, equipo_actual=?, cotizacion=?,  cedula=? WHERE id_jugador =?");

            pst.setString(1, txtnombres.getText().toUpperCase());
            pst.setString(2, txtapellidos.getText().toUpperCase());
            pst.setInt(3, Integer.parseInt(txtedad.getText()));
            pst.setInt(4, Integer.parseInt(txtpasaporte.getText()));

            int seleccionado = cboposicion.getSelectedIndex();
            pst.setString(5, cboposicion.getItemAt(seleccionado));

            pst.setString(6, txtdebug.getText().toUpperCase());
            pst.setString(7, txtactual.getText().toUpperCase());
            pst.setDouble(8, Double.parseDouble(txtcotizacion.getText()));
            pst.setInt(9, Integer.parseInt(txtcedula.getText()));
            pst.setInt(10, Integer.parseInt(id_jugador.getText()));
            pst.executeQuery();
            JOptionPane.showConfirmDialog(this, "Datos de Jugador Editado", "Confirmación", 2);
        } catch (SQLException exc) {
            //  JOptionPane.showMessageDialog(null,exc.getMessage(),"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Eliminar() {
        Conexion con = new Conexion();
        try {
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareStatement("DELETE FROM jugador WHERE id_jugador =" + id_jugador.getText());
            pst.executeQuery();
            JOptionPane.showConfirmDialog(this, "Jugador Eliminado", "Confirmación", 2);
        } catch (SQLException exc) {
            //JOptionPane.showMessageDialog(null, exc.getMessage(), "WARNING", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Consultar() {
        Conexion con = new Conexion();
        try {
            Connection conex = con.Open();
            PreparedStatement pst = conex.prepareCall("SELECT * FROM jugador where cedula = " + txtcedula.getText());
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                id_jugador.setText(rs.getString(1));
                txtnombres.setText(rs.getString(2));
                txtapellidos.setText(rs.getString(3));
                txtedad.setText(rs.getString(4));
                txtpasaporte.setText(rs.getString(5));
                cboposicion.setSelectedItem(rs.getString(6));
                txtdebug.setText(rs.getString(7));
                txtactual.setText(rs.getString(8));
                txtcotizacion.setText(rs.getString(9));
                txtcedula.setText(rs.getString(10));

            } else {
                JOptionPane.showMessageDialog(null, "NO SE ENCONTRO FUTBOLISTA", "BOOK NOT FOUND", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException exc) {
            //JOptionPane.showMessageDialog(null,exc,"WARNING",JOptionPane.ERROR_MESSAGE);
        }
    }

    public void Limpiar() {
        id_jugador.setText("");
        txtnombres.setText("");
        txtapellidos.setText("");
        txtedad.setText("");
        txtpasaporte.setText("");
        cboposicion.setSelectedIndex(-0);
        txtdebug.setText("");
        txtactual.setText("");
        txtcotizacion.setText("");
        txtcedula.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jugador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<String> cboposicion;
    private javax.swing.JPanel fondo;
    private javax.swing.JTextField id_jugador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtactual;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcotizacion;
    private javax.swing.JTextField txtdebug;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombres;
    private javax.swing.JTextField txtpasaporte;
    // End of variables declaration//GEN-END:variables
}
